# Generated by Django 5.2.8 on 2025-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_owner_alter_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
